config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'questions#index'

  resources :users do
    resources :answers, only: [:index]
    resources :hitokoto
  end

  resources :ranking, only: [:index]

  resources :questions do
    resources :answers, only: [:create] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :categorys, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_one :hitokoto
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.find(params[:format])
    @questions = @user.questions.all.order("id DESC")
    @categorys = Category.all
  end

  def show
    @user = User.find(params[:id])
    @questions = Question.where(user_id: current_user.id).order("id DESC")
    @categorys = Category.all
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.haml
.content
  .view 
    %h4 #{@user.nickname}さんのページ
  .questions
    .user_data
      .user_data__name
        .o-name お名前
        .user_data__name--nickname #{@user.nickname}
      .user_data__hitokoto
        .o-hitokoto ひとことメッセージ
        -if user_signed_in?
          -if @user.hitokoto != nil
            .user_data__hitokoto--comment= simple_format("#{@user.hitokoto.comment}")
            -if @user.id == current_user.id
              .user_data__hitokoto--edit= link_to "ひとことを編集する", edit_user_hitokoto_path(current_user.id, @user.hitokoto.id), method: :get
          -else 
            .user_data__hitokoto--comment 一言コメントはまだありません。
            -if @user.id == current_user.id
              .user_data__hitokoto--edit= link_to "ひとことを編集する", new_user_hitokoto_path(current_user.id), method: :get
        -else
          -if @user.hitokoto != nil
            .user_data__hitokoto--comment= simple_format("#{@user.hitokoto.comment}")
          -else
            .user_data__hitokoto--comment 一言コメントはまだありません。
      .user_data__question
        .user_data__question--nul 質問した数
        .user_data__question--count= @user.questions.count
      .user_data__answer
        .user_data__answer--nul 回答した数
        =link_to "#{@user.answers.count}", user_answers_path(@user), class: 'user_data__answer--count'
      .user_data__like
        .user_data__like--nul いいねした数
        .user_data__like--count= @user.likes.count
      .user_data__liked
        -liked_count = 0
        -@user.answers.each do |answer|
          -liked_count += answer.likes.count
        .user_data__liked--nul いいねされた数
        .user_data__liked--count= liked_count
    -@questions.each do |question|
      .question
        .question__text
          %p.question-helpman \^∆^/help~!!
          =link_to simple_format("#{question.title}"), question_path(question.id), method: :get, class: 'question__title' 
        .question__user
          %p.que-myname #{question.user.nickname}
          -# = link_to "#{question.user.nickname}", users_path(question.user.id), class: 'myname'
  .question_btn
    =link_to "助けを求める！!", new_question_path, class: 'rec'

app/views/users/show.html.haml
.content
  .view 
    %h4 マイページ(#{current_user.nickname})
  .questions
    .user_data
      .user_data__name
        .o-name お名前
        .user_data__name--nickname #{@user.nickname}
      .user_data__hitokoto
        .o-hitokoto ひとことメッセージ
        -if @user.hitokoto != nil
          .user_data__hitokoto--comment= simple_format("#{@user.hitokoto.comment}")
          .user_data__hitokoto--edit= link_to "ひとことを編集する", edit_user_hitokoto_path(current_user.id, @user.hitokoto.id), method: :get
        -else 
          .user_data__hitokoto--comment 一言コメントはまだありません
          .user_data__hitokoto--edit= link_to "ひとことを編集する", new_user_hitokoto_path(current_user.id), method: :get
      .user_data__question
        .user_data__question--nul 質問した数
        .user_data__question--count= @user.questions.count
      .user_data__answer
        .user_data__answer--nul 回答した数
        =link_to "#{@user.answers.count}", user_answers_path(@user), class: 'user_data__answer--count'
      .user_data__like
        .user_data__like--nul いいねした数
        .user_data__like--count= @user.likes.count
      .user_data__liked
        -liked_count = 0
        -@user.answers.each do |answer|
          -liked_count += answer.likes.count
        .user_data__liked--nul いいねされた数
        .user_data__liked--count= liked_count
    -@questions.each do |question|
      .question
        .question__text
          =link_to simple_format("#{question.title}"), question_path(question.id), method: :get, class: 'question__title' 
        .question__user
          =question.user.nickname
  .question_btn
    =link_to "助けを求める！!", new_question_path, class: 'rec'