config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'questions#index'

  resources :users do
    resources :answers, only: [:index]
    resources :hitokoto
  end

  resources :ranking, only: [:index]

  resources :questions do
    resources :answers, only: [:create] do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :categorys, only: [:show]
end

app/models/answer.rb
class Answer < ApplicationRecord

  belongs_to :user
  belongs_to :question
  has_many :likes, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :questions, dependent: :destroy
  # has_many :category_questions
  
end

app/models/category_question.rb
class CategoryQuestion < ApplicationRecord
end

app/models/hitokoto.rb
class Hitokoto < ApplicationRecord

  belongs_to :user

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :answer
end

app/models/question.rb
class Question < ApplicationRecord
  # acts_as_taggable_on :labels 
  # acts_as_taggable

  belongs_to :user
  has_many :answers, dependent: :destroy

  belongs_to :category
  # has_many :category_questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_one :hitokoto
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question, only: [:create]

  def index
    @user = User.find(params[:user_id])
    @answers = @user.answers.order("id DESC").page(params[:page]).per(20)
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user_id = current_user.id
    if @answer.save
      respond_to do |format|
        # format.html { redirect_back(fallback_location: root_path) }
        format.json
      end
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body).merge(question_id: @question)
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

end

app/controllers/categorys_controller.rb
class CategorysController < ApplicationController

  def show
    @cate = Category.find(params[:id])
    @category = @cate.questions.all.order("id DESC")
    @categorys = Category.all
  end

end

app/controllers/hitokoto_controller.rb
class HitokotoController < ApplicationController
  before_action :set_user

  def new
    @hitokoto = Hitokoto.new
  end

  def create
    @hitokoto = Hitokoto.new(hitokoto_params)
    if @hitokoto.save
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @hitokoto = Hitokoto.find(params[:id])
  end

  def update
    hitokoto = Hitokoto.find(params[:id])
    hitokoto.update(hitokoto_params) if hitokoto.user.id = current_user.id
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def hitokoto_params
    params.require(:@hitokoto).permit(:comment).merge(user_id: current_user.id)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_answer, only: [:show, :create, :destroy]

  def show
  end

  def create
    @like = Like.new(user_id: current_user.id, answer_id: params[:answer_id])
    if @like.save
      @likes = Like.where(answer_id: params[:answer_id])
      respond_to do |format|
        format.html {redirect_back(fallback_location: root_path)}
        format.json
      end
    end
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, answer_id: params[:answer_id])
    @like.destroy
    @likes = Like.where(answer_id: params[:answer_id])

    respond_to do |format|
      format.html {redirect_back(fallback_location: root_path)}
      format.json
    end
  end

  private

  def set_answer
    @answer = Answer.find(params[:answer_id])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_user, 

  def index
    @questions = Question.all.order("id DESC").page(params[:page]).per(20)
    @user = User.all
    @categorys = Category.all
  end

  def show
    @question = Question.find(params[:id])
    @user = @question.user
    @answer = Answer.new
  end

  def new
    if user_signed_in?
      @question = Question.new
    else
      redirect_to '/users/sign_in'
    end
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      respond_to do |format|
        format.html { redirect_to '/'}
        format.json
      end
    else
      redirect_to '/'
    end
  end

  def edit
  end

  def update
  end

  def destroy
    question = Question.find(params[:id])
    if question.user.id == current_user.id
      question.destroy
      redirect_to '/', alert: '削除?'
    end
  end

  private

  def question_params
    params.require(:@question).permit(:title, :body, :result, :category_id).merge(user_id: current_user.id)
  end

  def set_user
    @user = User.all
  end
  
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController

  def index
    @question_ranking = Question.find(Answer.group(:question_id).order('count(question_id)desc').limit(50).pluck(:question_id))
    @num = 1
    @numday = 1
    @numweek = 1
    @nummonth = 1
    @categorys = Category.all

    now = Time.current
    
    @question_ranking_today = Question.find(Answer.where(created_at: now.in_time_zone.all_day).group(:question_id).order('count(question_id)desc').limit(50).pluck(:question_id))
    @question_ranking_week = Question.find(Answer.where(created_at: now.in_time_zone.all_week).group(:question_id).order('count(question_id)desc').limit(50).pluck(:question_id))
    @question_ranking_month = Question.find(Answer.where(created_at: now.in_time_zone.all_month).group(:question_id).order('count(question_id)desc').limit(50).pluck(:question_id))
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.find(params[:format])
    @questions = @user.questions.all.order("id DESC")
    @categorys = Category.all
  end

  def show
    @user = User.find(params[:id])
    @questions = Question.where(user_id: current_user.id).order("id DESC")
    @categorys = Category.all
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categorys_helper.rb
module CategorysHelper
end

app/helpers/hitokoto_helper.rb
module HitokotoHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/index.html.haml
.content
  .view 
    %h4 #{@user.nickname}さんの回答一覧
  .questions
    -@answers.uniq.each do |answer|
      .question
        .question__text
          %p.question-helpman \^∆^/ﾀｽｹﾀ!!
          =link_to simple_format("#{answer.body}"), question_path(answer.question.id), method: :get, class: 'question__title'
        .question__user
          -if user_signed_in?
            -if answer.question.user.id != current_user.id
              = link_to "#{answer.question.user.nickname}", users_path(answer.question.user.id), class: 'myname'
            -else 
              %p.que-myname #{answer.question.user.nickname}(あなたです)
          -else
            = link_to "#{answer.question.user.nickname}", users_path(answer.question.user.id), class: 'myname'
    = paginate(@answers)
  .question_btn
    =link_to "助けを求める！!", new_question_path, class: 'rec'

app/views/categorys/show.html.haml
.content
  .view 
    %h4 質問投稿一覧 (#{@cate.name})
  .questions
    -@category.each do |question|
      .question
        .question__text
          %p.question-helpman \^∆^/help~!!
          =link_to simple_format("#{question.title}"), question_path(question.id), method: :get, class: 'question__title'
        .question__user
          -if user_signed_in?
            -if question.user.id != current_user.id
              = link_to "#{question.user.nickname}", users_path(question.user.id), class: 'myname'
            -else 
              %p.que-myname #{question.user.nickname}(あなたです)
          -else
            = link_to "#{question.user.nickname}", users_path(question.user.id), class: 'myname'
  .question_btn
    =link_to "助けを求める！!", new_question_path, class: 'rec'

app/views/hitokoto/edit.html.haml
.content
  =form_for '@hitokoto', url: { :controller => :hitokoto, :action => :update },  method: :patch do |f|
    =f.label 'ひとことメッセージ' ,class: 'hito_messe'
    =f.text_area :comment, class: 'form-hitokoto', placeholder: '入力してください(200文字以内)', size: "100x10", maxlength: "200"
    =f.submit '更新する', class: 'hitokoto-submit-btn'

app/views/hitokoto/new.html.haml
.content
  =form_for '@hitokoto', url: { :controller => :hitokoto, :action => :create } do |f|
    =f.label 'ひとことメッセージ' ,class: 'hito_messe'
    =f.text_area :comment, class: 'form-hitokoto', placeholder: '入力してください(200文字以内)', size: "100x10", maxlength: "200"
    =f.submit '更新する', class: 'hitokoto-submit-btn'

app/views/questions/_side-ber.html.haml
.side-ber
  -if user_signed_in?
    .user_nav-grid-6
      = link_to "マイページ(#{current_user.nickname})", user_path(current_user.id), class: 'myname'
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "out"
  -else
    .gird-6
      = link_to "ログイン", new_user_session_path, class: "post"
      = link_to "新規登録", new_user_registration_path, class: "post"

  .ranking 
    = link_to "人気の質問はこちら", ranking_index_path, class: 'ranking'

  -if @categorys.present?
    %ul.category-selection
      %p.category-nal みんなの質問カテゴリー
      =link_to "全て", "/", class: "category-min" 
      -@categorys.each do |category|
        =link_to "#{category.name}", category_path(category.id), class: "category-min" 

app/views/questions/index.html.haml
.content
  .view 
    %h4 質問投稿一覧 (全て)
    -# %input{:onclick => "window.location.reload();", :type => "button", :value => "更新"}/
  .questions
    -@questions.each do |question|
      .question
        .question__text
          %p.question-helpman \^∆^/help~!!
          =link_to simple_format("#{question.title}"), question_path(question.id), method: :get, class: 'question__title'
        .question__user
          -if user_signed_in?
            -if question.user.id != current_user.id
              = link_to "#{question.user.nickname}", users_path(question.user.id), class: 'myname'
            -else 
              %p.que-myname #{question.user.nickname}(あなたです)
          -else
            = link_to "#{question.user.nickname}", users_path(question.user.id), class: 'myname'
    = paginate(@questions)
  .question_btn
    =link_to "助けを求める！!", new_question_path, class: 'rec'

app/views/questions/new.html.haml
.megami
.form
  =form_for '@question', url: { :controller => :questions, :action => :create } do |f|
    .form__input
      = f.label '解決したいこと', class: 'sss'
      = f.text_area :title, class: 'form-message', placeholder: '入力してください', size: "100x5"
    .form__input
      = f.label '自分で調べた内容', class: 'sss'
      = f.text_area :body, class: 'form-message', placeholder: '入力してください', size: "100x5"
    .form__input
      = f.label '仮説と検証作業の結果', class: 'sss'
      = f.text_area :result, class: 'form-message', placeholder: '入力してください', size: "100x5"
    .form__category
      = f.label 'カテゴリー'
      = f.collection_select :category_id, @categorys, :id, :name, class: 'cate'
    = f.submit '質問する!!', class: 'submit-btn'

app/views/questions/show.html.haml
.content-show
  =link_to "回答フォーム↓↓↓↓↓↓↓", "", class: "scroll-answer"
  .view 
    %h4 #{@question.user.nickname}さんを助けてあげて！！
  .usersquestion__body
    .nikoniko-messe 質問を削除&回答したくない(泣)ｸﾘｯｸ!!→→
    .nikoniko 
      .nikoniko__mark ＼ (^ o ^) ／
    .questionsCategory
      %p.questionsCategory__nal カテゴリー： 
      =link_to "#{@question.category.name}", category_path(@question.category.id), class: "questionsCategory__text"
      -if user_signed_in?
        -if @question.user.id == current_user.id
          =link_to "削除", question_path(@question), class: "questionsCategory__del", method: :delete, data: {confirm: "削除しますか？"} 
    .question-db
      %h6.question-form-rec 解決したいこと
      #post-font= simple_format(@question.title)
    .question-db
      %h6.question-form-rec 自分で調べた内容
      #post-font= simple_format(@question.body)
    .question-db
      %h6.question-form-rec 仮説と検証作業の結果
      #post-font= simple_format(@question.result)
    = link_to "#{@question.user.nickname}さんのページはこちら", users_path(@question.user.id), class: 'querstion-host'
    %p.question__time #{@question.created_at.strftime('%Y年%m月%d日 %H:%M')}
  .answers
    %h5.tenkoeitiran ~ ~ 天の声一覧 ~ ~
    -@question.answers.each do |answer|
      .answers-show
        .answer-user
          -if user_signed_in?
            -if @question.user_id != answer.user.id && answer.user_id != current_user.id
              = link_to "#{answer.user.nickname}", users_path(answer.user.id), class: 'answer-myname'
              - if Like.find_by(user_id: current_user.id, answer_id: answer.id)
                %span.like-count #{answer.likes.count}
                = link_to  question_answer_like_path(@question.id, answer.id), class: 'unlibtn', id: "#{answer.id}", method: :delete do
                  %span.fa.fa-heart.like-btn-unlike
              - else
                %span.like-count #{answer.likes.count}
                = link_to question_answer_likes_path(@question.id, answer.id), class: 'libtn', id: "#{answer.id}", method: :post do
                  %span.fa.fa-heart.like-btn
              %br/
            -elsif answer.user_id == current_user.id
              %p.answer-is-current_user #{current_user.nickname}(あなたです)
              - if Like.find_by(user_id: current_user.id, answer_id: answer.id)
                %span.like-count #{answer.likes.count}
                = link_to  question_answer_like_path(@question.id, answer.id), class: 'unlibtn', id: "#{answer.id}", method: :delete do
                  %span.fa.fa-heart.like-btn-unlike
              - else
                %span.like-count #{answer.likes.count}
                = link_to question_answer_likes_path(@question.id, answer.id), class: 'libtn', id: "#{answer.id}", method: :post do
                  %span.fa.fa-heart.like-btn
            -else 
              %p.answer-que-myname #{answer.user.nickname}(質問者様)
              - if Like.find_by(user_id: current_user.id, answer_id: answer.id)
                %span.like-count #{answer.likes.count}
                = link_to  question_answer_like_path(@question.id, answer.id), class: 'unlibtn', id: "#{answer.id}", method: :delete do
                  %span.fa.fa-heart.like-btn-unlike
              - else
                %span.like-count #{answer.likes.count}
                = link_to question_answer_likes_path(@question.id, answer.id), class: 'libtn', id: "#{answer.id}", method: :post do
                  %span.fa.fa-heart.like-btn
          -else
            = link_to "#{answer.user.nickname}", users_path(answer.user.id), class: 'answer-myname'

        .heaven-voice
          = simple_format(answer.body)
  .answer-form-gun
    %h5.comment-nal ~ ~ ~ ~ ~ 天の声を授ける ~ ~ \^v^/ﾀｽｹﾙﾖ!! ~ ~ ~ ~ ~
    -if user_signed_in?
      =form_for [@question, @answer] do |f|
        =f.text_area :body, class: 'answer-form', placeholder: '入力してください', size: "100x5"
        =f.submit "授ける", class: 'submit-btn'
    -else
      .rogin-anauns
        %p.no-rogin-answer ログインしないと回答できないよ！！
        %p.no-rogin-answer 新規登録してみんなを助けてあげよう！！
        = link_to "※ログインはこちら", new_user_session_path, class: "post-answer-no-login"
        = link_to "※新規登録はこちら", new_user_registration_path, class: "post-answer-no-login"
      